#!/bin/sh

# Source debconf library.
PATH=$PATH:.
if [ -e confmodule ]; then
  . confmodule
else
  . /usr/share/debconf/confmodule
fi

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	# purging debconf data
	echo Purging debconf data.. >&2
        db_purge || true
	echo Removing service.. >&2
        update-rc.d collectw remove >/dev/null || true #exit $?
fi
# End automatically added section

db_stop

exit 0
